import type { RealAirport } from './types.js';
// Bundled curated airport set, generated by `scripts/fetch-airports.mjs` from
// the public-domain OurAirports dataset (https://ourairports.com — CC0).
// Re-run the script to refresh.
import bundled from './airports.json';

const data = bundled as RealAirport[];

/** All bundled airports (~1100 large + qualifying medium airports worldwide). */
export function allAirports(): RealAirport[] {
  return data;
}

/** Look up by ICAO (case-insensitive). */
export function findAirportByIcao(icao: string): RealAirport | undefined {
  const k = icao.toUpperCase();
  return data.find((a) => a.icao === k);
}

/** Look up by IATA (case-insensitive). Returns first match — IATA codes are
 *  globally unique in practice but not strictly guaranteed to be in the data. */
export function findAirportByIata(iata: string): RealAirport | undefined {
  const k = iata.toUpperCase();
  return data.find((a) => a.iata === k);
}

/** Filter by ISO 3166-1 alpha-2 country code (e.g. "US", "GB", "DE"). */
export function airportsByCountry(country: string): RealAirport[] {
  const k = country.toUpperCase();
  return data.filter((a) => a.country === k);
}

/** Filter by OurAirports type. */
export function airportsByType(type: 'large_airport' | 'medium_airport' | 'small_airport'): RealAirport[] {
  return data.filter((a) => a.type === type);
}
