import type { Approach } from './types.js';
// Curated starter set. Only `name`, `airport`, `runway`, `type`, `finalCourseT`
// are populated — minimums, FAF, IAF, missed approach are left undefined and
// should be added by hand against authoritative AIPs when needed.
//
// Generated by `scripts/seed-approaches.mjs`. Re-run that script (or hand-edit
// the JSON) to extend the set.
import bundled from './approaches.json';

const data = bundled as Approach[];

export function allApproaches(): Approach[] {
  return data;
}

export function approachesByIcao(icao: string): Approach[] {
  const k = icao.toUpperCase();
  return data.filter((a) => a.airport === k);
}

export function approachesByRunway(icao: string, runway: string): Approach[] {
  const k = icao.toUpperCase();
  return data.filter((a) => a.airport === k && a.runway === runway);
}
